version: "2"
services:
  item-app:
    image: krisnn/item-app:v1
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - item-db
  item-db:
    image: mongo:3
    restart: always
    ports:
      - 27017
    volumes:
      - app-db:/data/db
volumes:
  app-db: